# ============================================================
# DACTA Novelty Catcher -- Windows Build Script
# Builds a standalone executable using PyInstaller
# Auto-generated by SIEMLess
# ============================================================
#
# Prerequisites:
#   - Python 3.10+ installed and in PATH
#   - pip install pyinstaller pyyaml requests numpy scikit-learn
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File build-windows.ps1
#
# ============================================================

param(
    [string]$PythonExe = "python",
    [string]$SourceDir = "src",
    [string]$OutputDir = "dist",
    [string]$AppName = "novelty-catcher"
)

$ErrorActionPreference = "Stop"

# -- Banner --
Write-Host ""
Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host "  DACTA Novelty Catcher -- Windows Build" -ForegroundColor Cyan
Write-Host "  Version 2.0.0" -ForegroundColor Cyan
Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host ""

# -- Check Python --
Write-Host "[1/6] Checking Python installation..." -ForegroundColor Yellow
try {
    $pyVer = & $PythonExe --version 2>&1
    Write-Host "  Found: $pyVer" -ForegroundColor Gray
} catch {
    Write-Host "  ERROR: Python not found. Install Python 3.10+ and add to PATH." -ForegroundColor Red
    exit 1
}

# -- Check pip packages --
Write-Host "[2/6] Checking required packages..." -ForegroundColor Yellow
$requiredPackages = @("pyinstaller", "pyyaml", "requests", "numpy", "scikit-learn")
foreach ($pkg in $requiredPackages) {
    $check = & $PythonExe -m pip show $pkg 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Host "  Installing $pkg..." -ForegroundColor Gray
        & $PythonExe -m pip install $pkg --quiet
        if ($LASTEXITCODE -ne 0) {
            Write-Host "  ERROR: Failed to install $pkg" -ForegroundColor Red
            exit 1
        }
    } else {
        Write-Host "  OK: $pkg" -ForegroundColor Gray
    }
}

# -- Verify source files --
Write-Host "[3/6] Verifying source files..." -ForegroundColor Yellow
$mainEntry = Join-Path $SourceDir "main.py"
if (-not (Test-Path $mainEntry)) {
    # If no src directory, look for main.py in current dir
    if (Test-Path "main.py") {
        $mainEntry = "main.py"
        Write-Host "  Found main.py in current directory" -ForegroundColor Gray
    } elseif (Test-Path "novelty_catcher.py") {
        $mainEntry = "novelty_catcher.py"
        Write-Host "  Found novelty_catcher.py in current directory" -ForegroundColor Gray
    } else {
        Write-Host "  ERROR: Cannot find main.py or novelty_catcher.py" -ForegroundColor Red
        Write-Host "  Expected location: $mainEntry" -ForegroundColor Red
        exit 1
    }
}
Write-Host "  Entry point: $mainEntry" -ForegroundColor Gray

# -- Clean previous build --
Write-Host "[4/6] Cleaning previous build artifacts..." -ForegroundColor Yellow
if (Test-Path "build") { Remove-Item "build" -Recurse -Force }
if (Test-Path $OutputDir) { Remove-Item $OutputDir -Recurse -Force }
if (Test-Path "$AppName.spec") { Remove-Item "$AppName.spec" -Force }
Write-Host "  Cleaned." -ForegroundColor Gray

# -- Build with PyInstaller --
Write-Host "[5/6] Building executable with PyInstaller..." -ForegroundColor Yellow
Write-Host "  This may take a few minutes..." -ForegroundColor Gray

$pyInstallerArgs = @(
    "-m", "PyInstaller",
    "--onefile",
    "--name", $AppName,
    "--distpath", $OutputDir,
    "--workpath", "build",
    "--clean",
    "--noconfirm"
)

# Add data files if they exist
$configDir = "config"
if (Test-Path $configDir) {
    $pyInstallerArgs += @("--add-data", "$configDir;config")
}

$modelsDir = "models"
if (Test-Path $modelsDir) {
    $pyInstallerArgs += @("--add-data", "$modelsDir;models")
}

# Add hidden imports for common dependencies
$hiddenImports = @(
    "sklearn", "sklearn.ensemble", "sklearn.preprocessing",
    "numpy", "yaml", "requests", "json", "logging",
    "socket", "threading", "queue", "hashlib"
)
foreach ($imp in $hiddenImports) {
    $pyInstallerArgs += @("--hidden-import", $imp)
}

# Add the entry point
$pyInstallerArgs += $mainEntry

& $PythonExe $pyInstallerArgs
if ($LASTEXITCODE -ne 0) {
    Write-Host "  ERROR: PyInstaller build failed." -ForegroundColor Red
    exit 1
}

# -- Verify output --
Write-Host "[6/6] Verifying build output..." -ForegroundColor Yellow
$exePath = Join-Path $OutputDir "$AppName.exe"
if (Test-Path $exePath) {
    $fileInfo = Get-Item $exePath
    $sizeMB = [math]::Round($fileInfo.Length / 1MB, 2)
    Write-Host ""
    Write-Host "==========================================================" -ForegroundColor Green
    Write-Host "  BUILD SUCCESS" -ForegroundColor Green
    Write-Host "  Output: $exePath" -ForegroundColor Green
    Write-Host "  Size:   $sizeMB MB" -ForegroundColor Green
    Write-Host "==========================================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "Next steps:" -ForegroundColor Cyan
    Write-Host "  1. Run install-windows.ps1 to install as a Windows service" -ForegroundColor Gray
    Write-Host "  2. Configure credentials in the env file" -ForegroundColor Gray
    Write-Host "  3. Start the service: Start-Service DACTANoveltyCatcher" -ForegroundColor Gray
} else {
    Write-Host "  ERROR: Expected output not found at $exePath" -ForegroundColor Red
    exit 1
}
