# ============================================================
# DACTA Novelty Catcher -- Windows Service Installer
# Installs the catcher as a Windows service using NSSM
# Auto-generated by SIEMLess
# ============================================================
#
# Usage (Run as Administrator):
#   powershell -ExecutionPolicy Bypass -File install-windows.ps1
#
# What this script does:
#   1. Creates installation directories
#   2. Copies the executable and config files
#   3. Downloads NSSM (Non-Sucking Service Manager) if needed
#   4. Registers the catcher as a Windows service
#   5. Creates environment variable file for credentials
#   6. Optionally starts the service
#
# ============================================================

param(
    [string]$InstallDir = "C:\ProgramData\DACTA\Novelty-Catcher",
    [string]$ServiceName = "DACTANoveltyCatcher",
    [string]$ServiceDisplayName = "DACTA Novelty Catcher",
    [string]$ExeName = "novelty-catcher.exe",
    [switch]$Uninstall
)

$ErrorActionPreference = "Stop"

$CONFIG_DIR = Join-Path $InstallDir "config"
$LOG_DIR    = Join-Path $InstallDir "logs"
$STATE_DIR  = Join-Path $InstallDir "state"
$BIN_DIR    = Join-Path $InstallDir "bin"
$NSSM_DIR   = Join-Path $InstallDir "nssm"

# -- Check Administrator --
function Test-Administrator {
    $currentUser = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($currentUser)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

if (-not (Test-Administrator)) {
    Write-Host "ERROR: This script must be run as Administrator." -ForegroundColor Red
    Write-Host "Right-click PowerShell and select 'Run as Administrator'." -ForegroundColor Yellow
    exit 1
}

# -- Banner --
Write-Host ""
Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host "  DACTA Novelty Catcher -- Windows Service Installer" -ForegroundColor Cyan
Write-Host "  Version 2.0.0" -ForegroundColor Cyan
Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host ""

# -- Uninstall mode --
if ($Uninstall) {
    Write-Host "Uninstalling $ServiceName..." -ForegroundColor Yellow

    # Stop service if running
    $svc = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
    if ($svc) {
        if ($svc.Status -eq "Running") {
            Write-Host "  Stopping service..." -ForegroundColor Gray
            Stop-Service -Name $ServiceName -Force
            Start-Sleep -Seconds 2
        }
        # Remove via NSSM if available
        $nssmExe = Join-Path $NSSM_DIR "nssm.exe"
        if (Test-Path $nssmExe) {
            & $nssmExe remove $ServiceName confirm
        } else {
            sc.exe delete $ServiceName
        }
        Write-Host "  Service removed." -ForegroundColor Green
    } else {
        Write-Host "  Service not found, skipping." -ForegroundColor Gray
    }

    # Optionally remove install directory
    $removeDir = Read-Host "Remove installation directory $InstallDir? (y/N)"
    if ($removeDir -eq "y" -or $removeDir -eq "Y") {
        if (Test-Path $InstallDir) {
            Remove-Item $InstallDir -Recurse -Force
            Write-Host "  Directory removed." -ForegroundColor Green
        }
    }

    # Remove from PATH
    $machinePath = [Environment]::GetEnvironmentVariable("PATH", [EnvironmentVariableTarget]::Machine)
    if ($machinePath -and $machinePath.Contains($BIN_DIR)) {
        $newPath = ($machinePath.Split(";") | Where-Object { $_ -ne $BIN_DIR }) -join ";"
        [Environment]::SetEnvironmentVariable("PATH", $newPath, [EnvironmentVariableTarget]::Machine)
        Write-Host "  Removed from system PATH." -ForegroundColor Green
    }

    Write-Host ""
    Write-Host "Uninstall complete." -ForegroundColor Green
    exit 0
}

# -- Step 1: Create directories --
Write-Host "[1/7] Creating installation directories..." -ForegroundColor Yellow
$dirs = @($InstallDir, $CONFIG_DIR, $LOG_DIR, $STATE_DIR, $BIN_DIR, $NSSM_DIR)
foreach ($dir in $dirs) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
        Write-Host "  Created: $dir" -ForegroundColor Gray
    } else {
        Write-Host "  Exists:  $dir" -ForegroundColor Gray
    }
}

# -- Step 2: Copy executable --
Write-Host "[2/7] Copying executable..." -ForegroundColor Yellow
$srcExe = Join-Path $PSScriptRoot "dist\$ExeName"
if (-not (Test-Path $srcExe)) {
    # Try current directory
    $srcExe = Join-Path $PSScriptRoot $ExeName
}
if (-not (Test-Path $srcExe)) {
    # Try dist subdirectory relative to script
    $srcExe = Join-Path (Split-Path $PSScriptRoot) "dist\$ExeName"
}
if (-not (Test-Path $srcExe)) {
    Write-Host "  WARNING: $ExeName not found. Skipping copy." -ForegroundColor Yellow
    Write-Host "  You will need to manually copy the executable to: $BIN_DIR" -ForegroundColor Yellow
} else {
    Copy-Item $srcExe -Destination $BIN_DIR -Force
    Write-Host "  Copied $ExeName to $BIN_DIR" -ForegroundColor Gray
}

# -- Step 3: Copy config files --
Write-Host "[3/7] Copying configuration files..." -ForegroundColor Yellow

# Copy config.yaml if present
$srcConfig = Join-Path $PSScriptRoot "config.yaml"
if (-not (Test-Path $srcConfig)) {
    $srcConfig = Join-Path $PSScriptRoot "windows.yaml"
}
if (Test-Path $srcConfig) {
    Copy-Item $srcConfig -Destination (Join-Path $CONFIG_DIR "config.yaml") -Force
    Write-Host "  Copied config.yaml" -ForegroundColor Gray
} else {
    Write-Host "  WARNING: No config.yaml found. You must create one in $CONFIG_DIR" -ForegroundColor Yellow
}

# Create env.cmd for credentials if it does not exist
$envFile = Join-Path $CONFIG_DIR "env.cmd"
if (-not (Test-Path $envFile)) {
    $envContent = @"
@echo off
REM DACTA Novelty Catcher -- Environment Variables
REM Edit this file with your Elastic credentials
REM
REM After editing, restart the service:
REM   net stop $ServiceName
REM   net start $ServiceName

set ELASTIC_URL=https://your-elastic-instance:9200
set ELASTIC_API_KEY=your-api-key-here
set SIEMLESS_URL=https://dacta-siemless.vercel.app
set SIEMLESS_API_KEY=
set NC_LOG_LEVEL=INFO
"@
    Set-Content -Path $envFile -Value $envContent -Encoding ASCII
    Write-Host "  Created env.cmd template" -ForegroundColor Gray
    Write-Host "  IMPORTANT: Edit $envFile with your Elastic credentials" -ForegroundColor Yellow
} else {
    Write-Host "  env.cmd already exists, not overwriting" -ForegroundColor Gray
}

# Create env.ps1 for PowerShell-based environment loading
$envPs1File = Join-Path $CONFIG_DIR "env.ps1"
if (-not (Test-Path $envPs1File)) {
    $envPs1Content = @"
# DACTA Novelty Catcher -- Environment Variables (PowerShell format)
# Edit this file with your Elastic credentials

`$env:ELASTIC_URL = "https://your-elastic-instance:9200"
`$env:ELASTIC_API_KEY = "your-api-key-here"
`$env:SIEMLESS_URL = "https://dacta-siemless.vercel.app"
`$env:SIEMLESS_API_KEY = ""
`$env:NC_LOG_LEVEL = "INFO"
"@
    Set-Content -Path $envPs1File -Value $envPs1Content -Encoding ASCII
    Write-Host "  Created env.ps1 template" -ForegroundColor Gray
} else {
    Write-Host "  env.ps1 already exists, not overwriting" -ForegroundColor Gray
}

# -- Step 4: Add to system PATH --
Write-Host "[4/7] Updating system PATH..." -ForegroundColor Yellow
$machinePath = [Environment]::GetEnvironmentVariable("PATH", [EnvironmentVariableTarget]::Machine)
if ($machinePath -and (-not $machinePath.Contains($BIN_DIR))) {
    [Environment]::SetEnvironmentVariable("PATH", "$machinePath;$BIN_DIR", [EnvironmentVariableTarget]::Machine)
    Write-Host "  Added to system PATH: $BIN_DIR" -ForegroundColor Gray
} else {
    Write-Host "  Already in PATH" -ForegroundColor Gray
}

# -- Step 5: Download NSSM --
Write-Host "[5/7] Setting up NSSM (service manager)..." -ForegroundColor Yellow
$nssmExe = Join-Path $NSSM_DIR "nssm.exe"
if (-not (Test-Path $nssmExe)) {
    Write-Host "  Downloading NSSM 2.24..." -ForegroundColor Gray
    $nssmUrl = "https://nssm.cc/release/nssm-2.24.zip"
    $nssmZip = Join-Path $env:TEMP "nssm-2.24.zip"
    $nssmExtract = Join-Path $env:TEMP "nssm-2.24"

    try {
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri $nssmUrl -OutFile $nssmZip -UseBasicParsing
        Expand-Archive -Path $nssmZip -DestinationPath $env:TEMP -Force

        # Copy the correct architecture
        $arch = if ([Environment]::Is64BitOperatingSystem) { "win64" } else { "win32" }
        $nssmSrc = Join-Path $nssmExtract "$arch\nssm.exe"
        if (-not (Test-Path $nssmSrc)) {
            $nssmSrc = Join-Path "$nssmExtract\nssm-2.24" "$arch\nssm.exe"
        }
        if (Test-Path $nssmSrc) {
            Copy-Item $nssmSrc -Destination $nssmExe -Force
            Write-Host "  NSSM installed to $nssmExe" -ForegroundColor Gray
        } else {
            Write-Host "  WARNING: Could not find nssm.exe in downloaded archive" -ForegroundColor Yellow
            Write-Host "  Download manually from https://nssm.cc and place nssm.exe in $NSSM_DIR" -ForegroundColor Yellow
        }

        # Cleanup
        if (Test-Path $nssmZip) { Remove-Item $nssmZip -Force }
        if (Test-Path $nssmExtract) { Remove-Item $nssmExtract -Recurse -Force }
    } catch {
        Write-Host "  WARNING: Failed to download NSSM: $_" -ForegroundColor Yellow
        Write-Host "  Download manually from https://nssm.cc and place nssm.exe in $NSSM_DIR" -ForegroundColor Yellow
    }
} else {
    Write-Host "  NSSM already present" -ForegroundColor Gray
}

# -- Step 6: Register Windows service --
Write-Host "[6/7] Registering Windows service..." -ForegroundColor Yellow
$existingSvc = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($existingSvc) {
    Write-Host "  Service already exists. Updating..." -ForegroundColor Gray
    if ($existingSvc.Status -eq "Running") {
        Stop-Service -Name $ServiceName -Force
        Start-Sleep -Seconds 2
    }
    if (Test-Path $nssmExe) {
        & $nssmExe remove $ServiceName confirm 2>$null
    } else {
        sc.exe delete $ServiceName 2>$null
    }
    Start-Sleep -Seconds 1
}

$catcherExe = Join-Path $BIN_DIR $ExeName
$configPath = Join-Path $CONFIG_DIR "config.yaml"
$envCmdPath = Join-Path $CONFIG_DIR "env.cmd"

if (Test-Path $nssmExe) {
    # Install via NSSM with a wrapper script
    $wrapperBat = Join-Path $BIN_DIR "start-catcher.bat"
    $wrapperContent = @"
@echo off
REM DACTA Novelty Catcher service wrapper
call "$envCmdPath"
"$catcherExe" -c "$configPath" -m monitor
"@
    Set-Content -Path $wrapperBat -Value $wrapperContent -Encoding ASCII

    & $nssmExe install $ServiceName $wrapperBat
    & $nssmExe set $ServiceName DisplayName $ServiceDisplayName
    & $nssmExe set $ServiceName Description "DACTA Novelty Catcher - anomaly detection agent for SIEMLess platform"
    & $nssmExe set $ServiceName Start SERVICE_AUTO_START
    & $nssmExe set $ServiceName AppStdout (Join-Path $LOG_DIR "service-stdout.log")
    & $nssmExe set $ServiceName AppStderr (Join-Path $LOG_DIR "service-stderr.log")
    & $nssmExe set $ServiceName AppRotateFiles 1
    & $nssmExe set $ServiceName AppRotateBytes 10485760
    & $nssmExe set $ServiceName AppDirectory $InstallDir

    Write-Host "  Service registered via NSSM" -ForegroundColor Gray
} else {
    # Fallback: register via sc.exe
    $binPath = "`"$catcherExe`" -c `"$configPath`" -m monitor"
    sc.exe create $ServiceName binPath= $binPath start= auto displayname= $ServiceDisplayName
    sc.exe description $ServiceName "DACTA Novelty Catcher - anomaly detection agent for SIEMLess platform"
    Write-Host "  Service registered via sc.exe" -ForegroundColor Gray
    Write-Host "  NOTE: Without NSSM, environment variables from env.cmd will not auto-load." -ForegroundColor Yellow
    Write-Host "  Set them as system environment variables manually." -ForegroundColor Yellow
}

# -- Step 7: Summary --
Write-Host ""
Write-Host "==========================================================" -ForegroundColor Green
Write-Host "  INSTALLATION COMPLETE" -ForegroundColor Green
Write-Host "==========================================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Install Dir:  $InstallDir" -ForegroundColor Gray
Write-Host "  Executable:   $catcherExe" -ForegroundColor Gray
Write-Host "  Config:       $configPath" -ForegroundColor Gray
Write-Host "  Credentials:  $envCmdPath" -ForegroundColor Gray
Write-Host "  Logs:         $LOG_DIR" -ForegroundColor Gray
Write-Host "  Service Name: $ServiceName" -ForegroundColor Gray
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Edit credentials:   notepad $envCmdPath" -ForegroundColor White
Write-Host "  2. Edit config:        notepad $configPath" -ForegroundColor White
Write-Host "  3. Bootstrap learning:" -ForegroundColor White
Write-Host "     $catcherExe -c `"$configPath`" -m learn-from-elastic --learn-hours 168" -ForegroundColor DarkCyan
Write-Host "  4. Start service:      Start-Service $ServiceName" -ForegroundColor White
Write-Host "  5. Check status:       Get-Service $ServiceName" -ForegroundColor White
Write-Host "  6. View logs:          Get-Content $LOG_DIR\service-stdout.log -Wait" -ForegroundColor White
Write-Host ""
Write-Host "To uninstall:" -ForegroundColor Yellow
Write-Host "  powershell -File install-windows.ps1 -Uninstall" -ForegroundColor Gray
Write-Host ""
